### ISSUE TITLE
Attribut error while loading the model_2048_attn.pickle model in make_dlnd_data.py

### ISSUE THREAD

**Issue by chanchalIITP** [edithal-14/A-Deep-Neural-Solution-To-Document-Level-Novelty-Detection-COLING-2018-#1]
I have downloaded the DNLD dataset from "http://www.iitp.ac.in/~ai-nlp-ml/resources.html". 
In make_dlnd_data.py:
In the first line  "sys.path.append ()", I have put the path till the encoder directory of sentence_encoder. 
I put the path of dataset in the place of dlnd_path, 
I path the path of "model_2048_attn.pickle" in the infersent = torch.load(), and path of Glove in the glove_path line. While running it gives the error in loading the model . The error message is -

loading infersent...
Traceback (most recent call last):
  File "make_dlnd_data.py", line 36, in <module>
    infersent = torch.load("/home/mtp-2/Desktop/New_Coling/A-Deep-Neural-Solution-To-Document-Level-Novelty-Detection-COLING-2018--master/sentence_encoder/encoder/model_2048_attn.pickle")
  File "/home/mtp-2/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 358, in load
    return _load(f, map_location, pickle_module)
  File "/home/mtp-2/anaconda2/lib/python2.7/site-packages/torch/serialization.py", line 542, in _load
    result = unpickler.load()
AttributeError: 'module' object has no attribute 'InnerAttentionNAACLEncoder'

I have searched for the solution of this error, but could not get the answer.
It would be great, if you will help me.

**Comment by edithal-14** [comment]
Use the infersent module prvoided with this repo, the sentence_encoder directory contains the old infersent code. The new infersent repo does not support the Inner attention encoder.

Closing this.
