### ISSUE TITLE
Multiple issues with code compatibility

### ISSUE THREAD

**Issue by Manajit89** [edithal-14/A-Deep-Neural-Solution-To-Document-Level-Novelty-Detection-COLING-2018-#2]
Hi,

First of all thank you for providing the code alongside your COLING paper. We wanted to run your provided code on the WEBIS data for a personal project. Unfortunately, I am running into several compatibility issues such as with CUDA, Tensorflow and Theano. Since, I had CUDA 9.0 installed I had to resort to Python 2.7, which now has issues with NLTK while running the codes. Can you kindly specify the versions of each of the following software/packages that are required to run your code?

1. Python
2. Tensorflow (is it required only to run Keras?)
3. Theano
4. NLTK 
5. CUDA
6. Keras
7. PyTorch

Also, I noticed that in the Readme file, you have mentioned to use _make_dlnd_data.py_ under WEBIS heading to fetch the sentence embeddings (see attached screenshot).
![Novelty_issue](https://user-images.githubusercontent.com/33542824/76338896-aa31f180-62f9-11ea-94dd-c1c8b7478e3e.png)

That doesn't seem right. Is the corresponding file missing for webis_cpc?
Because, when I try to run _webis_sentence_embedding.py_, it throws an error asking for path to _webis_data.pickle, which is supposed to be generated with some other code, right?

Corollary to the above question, could you kindly specify in the documentation or maybe as a command line exception, what arguments need to be passed for each python file? That would make our lives a lot easier.

Any additional help is welcome.

Thanking in anticipation,
Manajit

**Comment by edithal-14** [comment]
Hi Manajit,

Thanks for taking time to read our work, really appreciate it. I believe the issues you have raised are genuine and I will gladly help you with it.

As far as I know there should be no dependency between CUDA and NLTK,  you should be good with the latest version of NLTK for python 2.7 and downgrade as necessary if you encounter any errors. I updated the README to list the version string for various dependencies, not sure about the version of theano, I guess version 1.0.0 (which was the stable version in late 2017 when I was working on this) should work. 

Also, updated the Webis section with info about various scripts. I have specified input and output dependencies for each script which should give you a good idea of the workflow. Note that input and output file names are hardcoded so you will have to edit the code as you wish.
I simply don't have the time to add argument handling to the scripts and write docstring for them, so you will have to deal with it by grepping the filenames to understand how they are being used.

Thanks,
Vignesh
